DROP SCHEMA IF EXISTS NOTEMANAGER;

CREATE SCHEMA IF NOT EXISTS NOTEMANAGER
CHARACTER SET utf8;

USE NOTEMANAGER;


CREATE TABLE NOTES (
  ID INT NOT NULL AUTO_INCREMENT,
  NOTE_TITLE VARCHAR(255) NOT NULL,
  NOTE_AUTHOR VARCHAR(255) NOT NULL,
  NOTE_DATA VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID));
