INSERT INTO NOTEMANAGER.NOTES (ID, NOTE_TITLE, NOTE_AUTHOR, NOTE_DATA) VALUES ('1', 'First Note', 'First Author', '3.3.2017');
INSERT INTO NOTEMANAGER.NOTES (ID, NOTE_TITLE, NOTE_AUTHOR, NOTE_DATA) VALUES ('2', 'Second Note', 'Second Author', '3.3.2017');
INSERT INTO NOTEMANAGER.NOTES (ID, NOTE_TITLE, NOTE_AUTHOR, NOTE_DATA) VALUES ('3', 'Third Note', 'Third Author', '3.3.2017');
INSERT INTO NOTEMANAGER.NOTES (ID, NOTE_TITLE, NOTE_AUTHOR, NOTE_DATA) VALUES ('4', 'Fourth Note', 'Fourth Author', '3.3.2017');
INSERT INTO NOTEMANAGER.NOTES (ID, NOTE_TITLE, NOTE_AUTHOR, NOTE_DATA) VALUES ('5', 'Fifth Note', 'Fifth Author', '3.3.2017');
INSERT INTO NOTEMANAGER.NOTES (ID, NOTE_TITLE, NOTE_AUTHOR, NOTE_DATA) VALUES ('6', 'Sixth Note', 'Sixth Author', '3.3.2017');
